### ISSUE TITLE
Simulator

### ISSUE THREAD

**Issue by yihang-xdu** [abliao/PIVOT-R#3]
Dear Authors,

When I run the command ./HARIX_RDKSim.sh -graphicsadapter=0 -port=30007 -RenderOffScreen, an error occurs:

[2024.12.03-22.58.05:897][  0]LogHAL: Error: FUnixPlatformProcess::CreateProc: File does not exist (/home/wuaming/PIVOT-R-main/SeaWave/Engine/Binaries/Linux/CrashReportClient).

I'm not sure if some files are missing from the installation package.

**Comment by abliao** [comment]
"LogHAL: Error: FUnixPlatformProcess::CreateProc: File does not exist" is not a real error. You can check the specific error information in the log. According to our test, after unzipping the file and running the command, it can run successfully directly without needing an additional installation package.
In addition, we tested it on Ubuntu 22.04. This simulator is built on UE5 and is not guaranteed to run on other Ubuntu versions.
